name: Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: yarn Install dependencies
      run: yarn
      

    - name: Build dist
      run: npm run build

    - name: Publish to npm registry
      run: |
        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DATABEND_TOKEN_NPM_VUE }}
      

